---
# Tasks for users role
- name: Create non-priv user
  user: name={{ non_priv_user }} generate_ssh_key=yes ssh_key_bits=2048
  when: non_priv_user is defined

- name: Install developer keys for non-priv user
  copy: >
      src={{ dev_keys }}
      dest=/home/{{ non_priv_user }}/.ssh/authorized_keys
      owner={{ non_priv_user }}
      group={{ non_priv_user }}
      mode=0600
  when: non_priv_user is defined and dev_keys is defined

- name: Create admin user
  user: name={{ ops_user }} generate_ssh_key=yes ssh_key_bits=2048
  when: ops_user is defined

- name: Install admin keys for devops
  copy: >
      src={{ ops_keys }}
      dest=/home/{{ ops_user }}/.ssh/authorized_keys
      owner={{ ops_user }}
      group={{ ops_user }}
      mode=0600
  when: ops_user is defined and ops_keys is defined

- name: Add admin user to sudoers list
  lineinfile: >
      dest=/etc/sudoers
      regexp='^{{ ops_user }}'
      line='{{ ops_user }} ALL=(ALL) NOPASSWD: ALL'
      state=present
      validate='visudo -cf %s'
  when: ops_user is defined
