---
# Tasks for users role
# Expects user objects with the following keys:
# username, keys_generate, keys_bits, keys_authorized, is_admin
- name: Create user accounts
  user: >
    name={{ item.username }}
    generate_ssh_key={{ item.keys_generate|default(true) }}
    ssh_key_bits={{ item.keys_bits|default(2048) }}
  with_items: users

- name: Install user keys
  copy: >
      src={{ item.keys_authorized }}
      dest=/home/{{ item.username }}/.ssh/authorized_keys
      owner={{ item.username }}
      group={{ item.username }}
      mode=0600
  with_items: users
  when: item.keys_authorized is defined

- name: Add admins to sudoers group
  lineinfile: >
      dest=/etc/sudoers
      regexp='^{{ item.username }}'
      line='{{ item.username }} ALL=(ALL) NOPASSWD: ALL'
      state=present
      validate='visudo -cf %s'
  with_items: users
  when: item.is_admin is defined and item.is_admin
