# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "chef/centos-7.0"
  config.vm.provision "ansible" do |ansible|

      ansible.playbook = "site.yml"
      ansible.sudo = true
      ansible.extra_vars = {
          users: [
              { username: 'foo' },
              { username: 'bar', keys_generate: true },
              { username: 'baz', keys_generate: true, keys_bits: 4086 },
              { username: 'bif', keys_authorized: "~/.ssh/id_rsa.pub" },
              { username: 'thud', is_admin: true }
          ]
      }

  end
end
